### ISSUE TITLE
SME Review Checklist

### ISSUE THREAD

**Issue by jonathanxue** [OpenLiberty/draft-guide-jax-rs-reactive-client#18]
SME Review:

Review of the guide by a Subject Matter Expert (SME) for technical accuracy and content.

- [ ] Ensure technical accuracy for code
- [ ] Ensure technical accuracy for guide
- [ ] Ensure technical accuracy for overall content

 https://draft-guides.mybluemix.net/guides/jaxrs-reactive-client.html

**Comment by jkoehler22** [comment]
RxObservableInvoker is a Jersey Observable Invoker.  I would suggest that CXFs ObservableRxInvoker should be used in the guide as Liberty uses CXF.

**Comment by jkoehler22** [comment]
I need to state the same thing I stated in #13 

_Since this is a reactive guide, I suggest you describe reactive programming. I also suggest you explain what is improved over asynchronous programming._

**Comment by jkoehler22** [comment]
The cloning failed:

$ **git clone https://github.com/openliberty/guide-jaxrs-reactive-client.git**
Cloning into 'guide-jaxrs-reactive-client'...
Logon failed, use ctrl+c to cancel basic credential prompt.
Username for 'https://github.com':
Password for 'https://github.com':
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/openliberty/guide-jaxrs-reactive-client.git/'

git clone git@github.com:OpenLiberty/draft-guide-jax-rs-reactive-client.git worked.

So the cloning should be:
**git clone git@github.com:OpenLiberty/guide-jax-rs-reactive-client.git**

**Comment by jkoehler22** [comment]
Please note in **What you'll learn**  that this guide will be using the Jersey Provider and that other providers will use different invockers.

**Comment by jkoehler22** [comment]
Reactive programming is a **extension to** asynchronous programming  and a paradigm where data availability controls execution **that avoids overwhelming the consumer.**
